repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8 --exclude .venv
        language: system
        types: [python]
      - id: black
        name: black
        entry: poetry run black src/
        language: system
        types: [python]
      - id: pylint
        name: pylint
        entry: poetry run pylint src/
        language: system
        types: [python]
      - id: bandit
        name: bandit
        entry: poetry run bandit
        args: [
          "-r",
          "-c", "pyproject.toml",
          "-v",
          "src/"
        ]
        language: system
        types: [python]
